name: Teaching Tools Demonstration

# Allow one concurrent deployment
concurrency:
  group: GitHub Pages
  cancel-in-progress: false

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - ".github/workflows/main.yml"
      - "**/**/PRESENTATION.md"
      - "**/**/QUIZ.md"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages and to release to GitHub Releases
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-upload-course-presentations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build presentations with Marp
        uses: docker://marpteam/marp-cli:v4.1.1
        with:
          entrypoint: sh
          args: generate-presentations.sh

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: course-presentations
          path: |
            **/*/*.jpg
            **/*/*.jpeg
            **/*/*.png
            **/*/*.svg
            **/*/*-presentation.pdf
            **/*/*-quiz.pdf
            **/*/presentation.html
            **/*/quiz.html
          if-no-files-found: error
          retention-days: 1

  create-index-page-for-github-pages:
    runs-on: ubuntu-latest
    needs: build-and-upload-course-presentations
    steps:
      - name: Download course presentations
        uses: actions/download-artifact@v4
        with:
          name: course-presentations

      - name: Install packages
        run: sudo apt install --yes tree

      - name: Generate index.html with tree
        run: |
          tree -H '.' --noreport --dirsfirst -T 'Teaching Tools Demonstration' -P "*.html|*.pdf" --prune --charset utf-8 -o index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  publish-course-presentations-to-github-pages:
    needs: create-index-page-for-github-pages
    runs-on: ubuntu-latest
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  create-github-release:
    runs-on: ubuntu-latest
    needs: build-and-upload-course-presentations
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download course presentations
        uses: actions/download-artifact@v4
        with:
          name: course-presentations

      - name: Release course presentations to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          body: |
            This new version contains the presentations in PDF format for the Teaching Tools Demonstration repository.

            You can directly access the content of this version with the following Git tag: [`${{ github.ref_name }}`](${{ github.event.repository.html_url }}/tree/${{ github.ref_name }}).
          files: |
            **/*/*-presentation.pdf
